site_name: Book of Verse 
site_url: https://pages.github.ol.epicgames.net/verse/VerseBook
site_description: Documentation for the Verse programming language
site_author: Jan Vitek

repo_name: verse/VerseBook
repo_url: https://github.ol.epicgames.net/verse/VerseBook
edit_uri: edit/main/VerseBook/docs/

theme:
  name: material
  logo: images/verse.png
  palette:
    scheme: slate  # Dark theme
    primary: black
    accent: deep orange
  features:
#    - content.footnote.tooltips
#    - navigation.tabs
    - search.suggest

markdown_extensions:
 - admonition
 - pymdownx.details
 - footnotes
 - pymdownx.highlight:
      default_lang: verse
      linenums: false
      pygments_style: monokai
 - pymdownx.superfences

plugins:
  - search

extra_css:
  - extra.css

nav:
  - Home: index.md
  - Overview: 00_overview.md
  - Expressions: 01_expressions.md
  - Primitives types: 02_primitives.md
  - Containers types: 03_containers.md
  - Operators: 04_operators.md
  - Mutability: 05_mutability.md
  - Functions: 06_functions.md
  - Control Flow: 07_control.md
  - Failure: 08_failure.md
  - Structs & Enums: 09_structs_enums.md
  - Classes & Interfaces: 10_classes_interfaces.md
  - Type System: 11_types.md
  - Access Specifiers: 12_access.md
  - Effects: 13_effects.md
  - Concurrency: 14_concurrency.md
  - Live Variables: 15_live_variables.md
  - Modules and Paths: 16_modules.md
  - Persistable Types: 17_persistable.md
  - Code Evolution: 18_evolution.md
  - "ðŸ“š Concept Index": concept_index.md

